"""add salary records and history

Revision ID: a1ecfed74dad
Revises: bd7fba8ca8a0
Create Date: 2026-10-03 15:40:17.198904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ecfed74dad'
down_revision: Union[str, Sequence[str], None] = 'bd7fba8ca8a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('old_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('new_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('change_percentage', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_history_effective_date'), 'salary_history', ['effective_date'], unique=False)
    op.create_index(op.f('ix_salary_history_employee_id'), 'salary_history', ['employee_id'], unique=False)
    op.create_table('salary_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_records_effective_from'), 'salary_records', ['effective_from'], unique=False)
    op.create_index(op.f('ix_salary_records_employee_id'), 'salary_records', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_records_employee_id'), table_name='salary_records')
    op.drop_index(op.f('ix_salary_records_effective_from'), table_name='salary_records')
    op.drop_table('salary_records')
    op.drop_index(op.f('ix_salary_history_employee_id'), table_name='salary_history')
    op.drop_index(op.f('ix_salary_history_effective_date'), table_name='salary_history')
    op.drop_table('salary_history')
    # ### end Alembic commands ###
